coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false

github_checks:
  annotations: true
  wait_for_ci: false

ignore:
  - "tests/**"
  - "coverage/**"
  - "node_modules/**"
  - "*.test.js"
  - "*.spec.js"
